### ISSUE TITLE
terminate called after throwing an instance of 'LibError'

### ISSUE THREAD

**Issue by koh-osug** [louisroyer-docker/ueransim#22]
When starting with docker-compose (also with sudo) I get from Ubuntu 22.04:

~~~shell
Starting ueransim-ue ... done
Attaching to ueransim-ue
ueransim-ue    | [2023-08-03T17:49:15+00:00] Running template-script.sh for building /etc/ueransim/ue.yaml from /etc/ueransim/template-ue.yaml.
ueransim-ue    | UERANSIM v3.2.6
ueransim-ue    | [2023-08-03 17:49:15.584] [nas] [info] UE switches to state [MM-DEREGISTERED/PLMN-SEARCH]
ueransim-ue    | terminate called after throwing an instance of 'LibError'
ueransim-ue    |   what():  sendto failed:  Cannot assign requested address
~~~

**Comment by louisroyer** [comment]
Hi, please attach your `docker-compose.yaml` file. I can do nothing with just this log, and it is most likely a configuration issue since it works for me.

**Comment by louisroyer** [comment]
Values `127.0.0.1` and `::1` in the `README.md` where intended to be replaced by the IP of your gNBs. If you don't have any gNB there is no point in running an UE anyway.
I will replace those values with IPs from documentation reserved range to avoid confusion.

**Comment by koh-osug** [comment]
Thanks. I will update my IP, I thought it is linke somehow with the NET_ADMIN to the host system.
