### ISSUE TITLE
GNB: SCTP could not connect: Network is unreachable

### ISSUE THREAD

**Issue by koh-osug** [louisroyer-docker/ueransim#24]
I assume I make a simple error, but I cannot connect to the 5GC. I'm using free5gc running on the host and want to connect from the docker image. I tried `   extra_hosts:
      - "host.docker.internal:host-gateway"` to connect, but I have no success:

> ueransim-gnb    | [2023-08-04T23:48:57+00:00] Running template-script.sh for building /etc/ueransim/gnb.yaml from /etc/ueransim/template-gnb.yaml.
> ueransim-gnb    | UERANSIM v3.2.6
> ueransim-gnb    | [2023-08-04 23:48:57.812] [sctp] [info] Trying to establish SCTP connection... (172.17.0.1:38412)
> ueransim-gnb    | [2023-08-04 23:48:57.814] [sctp] [error] Connecting to 172.17.0.1:38412 failed. SCTP could not connect: Network is unreachable

I tried to start a server on my host with:

~~~shell
nc -l -u 0.0.0.0 55000
~~~

And a connection from within the running container succeeds:

~~~shell
nc -vz -u 172.17.0.1 55000
~~~

But the SCTP connection does not work.

This is the docker-compose file:

~~~yaml
version: '3.3'

services:
  ueransim-gnb:
    image: louisroyer/ueransim-gnb
    container_name: ueransim-gnb
    network_mode: bridge
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    command: [" "]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      MCC: "999"
      MNC: "70"
      NCI: "0x000000010"
      ID_LEN: 32
      TAC: 1
      # The following variable have no default values
      RLS_IP: "127.0.0.1"
      N2_IP: "127.0.0.1"
      N3_IP: "127.0.0.1"
      AMF_CONFIGS: |-
        - address: host.docker.internal
          port: 38412
      SUPPORTED_NSSAIS: |-
        - sst: 1
          sd: 0x010203
~~~

**Comment by louisroyer** [comment]
Modifying the value of `N2_IP` with the actual IP Address of your gNB should solve your issue. With your config, the IP of your gNB should be something like `172.17.0.2` (and I strongly recommend you to assign it manually using a `networks` block, especially if you have more than one container in the network).

**Comment by koh-osug** [comment]
In addition I had to use the host network interface IP, like 192.168.178.122 instead of `host.docker.internal`. It can be resolved, but a connection fails to it. It seems not to be bound also when using 0.0.0.0 as bind address in free5gc AMF.

**Comment by louisroyer** [comment]
When binding the AMF on wilcard (`0.0.0.0`), it logs something like:
```
2023-08-06T00:40:34.687463223+02:00 [INFO][AMF][Ngap] Listen on 127.0.0.1/[::1%lo]/192.168.1.10/[2a01:****:****:****:****:****:****:****%wlp1s0]/[fe80::8585:4b4f:8c74:2bcb%wlp1s0]/10.0.0.1/[fe80::42:c2ff:fe2a:5cd1%docker0]:38412
```

On my side, the connection works when binding to the wilcard and connecting to `host.docker.internal`. Maybe it's a firewall issue on your host? You could try to run an iperf3 in sctp on port 38412 to check this.

For questions regarding Free5GC configuration, you can also go to [their forum](https://forum.free5gc.org)
